import json
import codecs

with codecs.open('src/models/BGLC_KG_Model_Training.ipynb', 'r', 'utf-8') as f:
    data = json.load(f)

# Check if SOTA is already there
found = False
for c in data['cells']:
    if '9. State-of-the-Art' in ''.join(c.get('source', [])):
        found = True

if not found:
    sota_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 9. State-of-the-Art (SOTA) Knowledge Graph Embedding Benchmarking\n",
            "# This section trains 4 distinct high-quality, open-source KGE models (TransE, DistMult, ComplEx, RotatE) \n",
            "# using PyTorch Geometric to prove our HeteroGraphSAGE superiority.\n",
            "\n",
            "from torch_geometric.nn.kge import TransE, DistMult, ComplEx, RotatE\n",
            "\n",
            "print(\"\\n--- Initializing SOTA KGE Benchmarking (TransE, DistMult, ComplEx, RotatE) ---\")\n",
            "\n",
            "# 9.1 Convert HeteroData to Homogeneous format for KGE models\n",
            "num_nodes_total = sum([data[ntype].num_nodes for ntype in data.node_types])\n",
            "\n",
            "# Create global node mapping\n",
            "node_mapping = {}\n",
            "current_idx = 0\n",
            "for ntype in data.node_types:\n",
            "    node_mapping[ntype] = current_idx\n",
            "    current_idx += data[ntype].num_nodes\n",
            "    \n",
            "# Create relation mapping\n",
            "rel_mapping = {etype: i for i, etype in enumerate(data.edge_types)}\n",
            "num_relations = len(rel_mapping)\n",
            "\n",
            "# Generic KGE trainer function\n",
            "def train_kge_model(model_name, kge_model, epochs=20):\n",
            "    print(f\"Training {model_name}...\")\n",
            "    optimizer_kge = torch.optim.Adam(kge_model.parameters(), lr=0.01)\n",
            "    \n",
            "    # Prepare target test edges globally\n",
            "    test_edge_idx = data[target_edge].edge_index[:, data[target_edge].test_mask]\n",
            "    test_global_head = test_edge_idx[0] + node_mapping['drug']\n",
            "    test_global_tail = test_edge_idx[1] + node_mapping['disease']\n",
            "    target_rel_idx = torch.full((test_global_head.size(0),), rel_mapping[target_edge], dtype=torch.long).to(device)\n",
            "    \n",
            "    # Generate some negative test edges for AUC calculation\n",
            "    neg_test_tail = torch.randint(0, data['disease'].num_nodes, (test_global_head.size(0),)) + node_mapping['disease']\n",
            "    neg_test_tail = neg_test_tail.to(device)\n",
            "    \n",
            "    # Train loop\n",
            "    kge_model.train()\n",
            "    for epoch in range(epochs):\n",
            "        train_edge_idx = data[target_edge].edge_index[:, data[target_edge].train_mask]\n",
            "        head = train_edge_idx[0] + node_mapping['drug']\n",
            "        tail = train_edge_idx[1] + node_mapping['disease']\n",
            "        rel = torch.full((head.size(0),), rel_mapping[target_edge], dtype=torch.long)\n",
            "        \n",
            "        head, tail, rel = head.to(device), tail.to(device), rel.to(device)\n",
            "        optimizer_kge.zero_grad()\n",
            "        # PyG KGE automatically generates negative samples inside the loss function\n",
            "        loss = kge_model.loss(head, rel, tail)\n",
            "        loss.backward()\n",
            "        optimizer_kge.step()\n",
            "        \n",
            "    # Evaluate\n",
            "    kge_model.eval()\n",
            "    with torch.no_grad():\n",
            "        pos_scores = kge_model(test_global_head.to(device), target_rel_idx, test_global_tail.to(device))\n",
            "        neg_scores = kge_model(test_global_head.to(device), target_rel_idx, neg_test_tail)\n",
            "        \n",
            "        y_true = torch.cat([torch.ones_like(pos_scores), torch.zeros_like(neg_scores)]).cpu().numpy()\n",
            "        y_scores = torch.cat([pos_scores, neg_scores]).cpu().numpy()\n",
            "        \n",
            "        auc = roc_auc_score(y_true, y_scores)\n",
            "    return auc\n",
            "\n",
            "# Initialize Models\n",
            "hidden_dim_kge = 64\n",
            "sota_results = {\"Our HeteroGraphSAGE\": test_auc} # test_auc from Phase 5\n",
            "\n",
            "try:\n",
            "    transe = TransE(num_nodes=num_nodes_total, num_relations=num_relations, hidden_channels=hidden_dim_kge).to(device)\n",
            "    sota_results[\"TransE\"] = train_kge_model(\"TransE\", transe)\n",
            "    \n",
            "    distmult = DistMult(num_nodes=num_nodes_total, num_relations=num_relations, hidden_channels=hidden_dim_kge).to(device)\n",
            "    sota_results[\"DistMult\"] = train_kge_model(\"DistMult\", distmult)\n",
            "    \n",
            "    complex_model = ComplEx(num_nodes=num_nodes_total, num_relations=num_relations, hidden_channels=hidden_dim_kge).to(device)\n",
            "    sota_results[\"ComplEx\"] = train_kge_model(\"ComplEx\", complex_model)\n",
            "    \n",
            "    rotate = RotatE(num_nodes=num_nodes_total, num_relations=num_relations, hidden_channels=hidden_dim_kge).to(device)\n",
            "    sota_results[\"RotatE\"] = train_kge_model(\"RotatE\", rotate)\n",
            "    \n",
            "    # Generate SOTA Comparison Table & Plot\n",
            "    df_sota = pd.DataFrame(list(sota_results.items()), columns=['Model', 'Test ROC-AUC']).sort_values(by='Test ROC-AUC', ascending=False)\n",
            "    print(\"\\n--- SOTA Benchmarking Results ---\")\n",
            "    print(df_sota.to_string(index=False))\n",
            "    \n",
            "    plt.figure(figsize=(10, 6))\n",
            "    sns.barplot(data=df_sota, x='Test ROC-AUC', y='Model', palette='rocket')\n",
            "    plt.title('SOTA Knowledge Graph Models Comparison (Test Set)', fontweight='bold')\n",
            "    plt.xlabel('ROC-AUC Score')\n",
            "    plt.xlim(0.0, 1.0)\n",
            "    for index, value in enumerate(df_sota['Test ROC-AUC']): \n",
            "        plt.text(value + 0.01, index, f'{value:.3f}', va='center', fontweight='bold')\n",
            "    plt.tight_layout()\n",
            "    plt.savefig(os.path.join(VIS_DIR, 'sota_comparison.png'), dpi=300)\n",
            "    plt.show()\n",
            "except Exception as e:\n",
            "    print(f\"KGE Benchmarking skipped due to memory/version limits: {e}\")\n"
        ]
    }
    data['cells'].append(sota_cell)
    with codecs.open('src/models/BGLC_KG_Model_Training.ipynb', 'w', 'utf-8') as f:
        json.dump(data, f, indent=1, ensure_ascii=False)
